import { NextResponse } from "next/server";
import { getPublicBaseUrl } from "@/lib/twilio";

export const dynamic = "force-dynamic";

/**
 * Returns TwiML that plays hold music when a conference participant is put on
 * hold. Twilio calls this URL when `Hold=true` is set on a participant.
 *
 * Plays our own synthesized ambient loop (public/hold-music.wav — generated by
 * scripts/make-hold-music.mjs, royalty-free by construction). This used to
 * stream demo.twilio.com's sample mp3 to real customers on hold. loop="0"
 * repeats indefinitely until unheld; the <Pause> fallback keeps the hold alive
 * even if the asset URL can't be built (no public base URL configured).
 */
export async function GET(req: Request) {
  const base = getPublicBaseUrl(req);
  const inner = base
    ? `<Play loop="0">${base}/hold-music.wav</Play>`
    : `<Pause length="600"/>`;
  const twiml = `<?xml version="1.0" encoding="UTF-8"?>
<Response>
  ${inner}
</Response>`;
  return new NextResponse(twiml, {
    status: 200,
    headers: { "Content-Type": "text/xml" },
  });
}
